ЛР-5/Часть 2/App/urls.py
from django.urls import path
from . import views


app_name = 'App'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:animal_id>', views.detail, name='detail'),
    path('<int:animal_id>/leave_review', views.leave_review, name='leave_review')
]

ЛР-5/Часть 2/LAB_5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('App.urls')),
    path('admin/', admin.site.urls)
]

ЛР-5/Часть 2/App/models.py
from django.db import models


# Create your models here.
class Animal(models.Model):
    animal_type = models.CharField('Вид животного', max_length=50)
    animal_name = models.CharField('Кличка животного', max_length=50)
    animal_photo = models.URLField('Фото жифотного', max_length=200)

    def __str__(self):
        return f'Тип: {self.animal_type}; Имя: {self.animal_name}; URL фото: {self.animal_photo}'

    class Meta:
        verbose_name = 'Животное'
        verbose_name_plural = 'Животные'


class Animal_review(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    author = models.CharField('Имя автора', max_length=50)
    review_text = models.CharField('Текст отзыва', max_length=200)

    def __str__(self):
        return f'Автор: {self.author}, Отзыв: {self.review_text}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

ЛР-5/Часть 2/App/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Animal


def index(request):
    a_list = Animal.objects.all()
    return render(request, 'App/list.html', dict([('a_list', a_list)]))


def detail(request, animal_id):
    try:
        a = Animal.objects.get(id=animal_id)
    except:
        raise Http404('Животное не найдено!')
    reviews = a.animal_review_set.order_by('-id')
    return render(request, 'App/detail.html', dict([('animal', a), ('review_list', reviews)]))



def leave_review(request, animal_id):
    try:
        a = Animal.objects.get(id=animal_id)
    except:
        raise Http404('Животное не найдено!')
    a.animal_review_set.create(author=request.POST['name'], review_text=request.POST['text'])
    return HttpResponseRedirect(reverse('App:detail', args=(a.id,)))

ЛР-5/Часть 2/templates/App/detail.html
{% extends 'base.html' %}

{% block title %}{{ animal.animal_name}}{% endblock %}

{% block content %}

    <center><h1>{{ animal.animal_name }}</h1></center><hr><br>
{#    Вид животного: {{ animal.animal_type }}<br>#}
{#    Имя животного: {{ animal.animal_name }}<br>#}
{#    <br>#}
{#    Фото животного<br>#}
{#    <img src="{{ animal.animal_photo }}" alt="Фото животного не найдено">#}
    <table border="1" cellpadding="5">
    <tr>
        <th>Вид животного</th>
        <th>{{ animal.animal_type }}</th>
    </tr>
    <tr>
        <th>Имя животного</th>
        <th>{{ animal.animal_name }}</th>
    </tr>
    <tr>
        <th>Фото животного</th>
        <th><img src="{{ animal.animal_photo }}" alt="Фото животного не найдено"></th>
    </tr>
    </table>
    <br>
    <form action="{% url 'App:leave_review' animal.id %}" method="post">
    {% csrf_token %}
    <input type="text" required placeholder="Имя" name="name"><br>
    <textarea name="text" required="" placeholder="Текст отзыва" cols="30" rows="10"></textarea>
    <button type="submit">Отправить отзыв</button>

    </form><hr>

    {% if review_list %}
        <table border="1" cellpadding="5">
        <tr>
            <th>Автор</th>
            <th>Отзыв</th>
        </tr>
        {% for r in review_list %}
            <tr>
            <th>{{ r.author }}</th>
            <th>{{ r.review_text }}</th>
            </tr>
        {% endfor %}
        </table>
    {% else %}
    Отзывы не найдены! Оставьте первый!
    {% endif %}

    <hr><br>
    <a href="/">Назад</a>

{% endblock %}

ЛР-5/Часть 2/templates/App/list.html
{% extends 'base.html' %}

{% block title %}ЛР №5{% endblock %}

{% block content %}

    <center><h1>Список животных</h1></center><hr><br>

    {% if a_list %}
        <ul>
        {% for a in a_list %}
            <li><a href="{% url 'App:detail' a.id %}">{{ a.animal_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        Список пуст
    {% endif %}

{% endblock %}

ЛР-5/Часть 2/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Лабораторная работа № 5{% endblock %}</title>
</head>
<body>

{% block content %}{% endblock %}

<hr>
<center>Чиварзин А. Е. ИУ5Ц-72Б</center>

</body>
</html>