ЛР-4/LAB_4/LAB_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('master/', include('master.urls')),
    path('admin/', admin.site.urls)
]

ЛР-4/LAB_4/master/urls.py
from django.urls import path
from . import views


app_name = 'master'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:animal_id>', views.detail, name='detail')

]

ЛР-4/LAB_4/master/models.py
from django.db import models

# Create your models here.
class Animal(models.Model):
    animal_type = models.CharField('Вид животного', max_length=50)
    animal_name = models.CharField('Кличка животного', max_length=50)
    animal_photo = models.URLField('Фото жифотного', max_length=200)

    def __str__(self):
        return f'Тип: {self.animal_type}; Имя: {self.animal_name}; URL фото: {self.animal_photo}'

    class Meta:
        verbose_name = 'Животное'
        verbose_name_plural = 'Животные'

ЛР-4/LAB_4/master/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Animal


def index(request):
    a_list = Animal.objects.all()
    return render(request, 'master/list.html', dict([('a_list', a_list)]))

def detail(request, animal_id):
    try:
        a = Animal.objects.get(id=animal_id)
    except:
        raise Http404('Животное не найдено!')
    return render(request,'master/detail.html', dict([('animal', a)]))

ЛР-4/LAB_4/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Лабораторная работа № 4{% endblock %}</title>
</head>
<body>

{% block content %}{% endblock %}

<hr>
<center>Чиварзин А. Е. ИУ5Ц-72Б</center>

</body>
</html>

ЛР-4/LAB_4/templates/master/detail.html
{% extends 'base.html' %}

{% block title %}{{ animal.animal_name}}{% endblock %}

{% block content %}

    <center><h1>{{ animal.animal_name }}</h1></center><hr><br>
{#    Вид животного: {{ animal.animal_type }}<br>#}
{#    Имя животного: {{ animal.animal_name }}<br>#}
{#    <br>#}
{#    Фото животного<br>#}
{#    <img src="{{ animal.animal_photo }}" alt="Фото животного не найдено">#}
    <table border="1" cellpadding="5">
    <tr>
        <th>Вид животного</th>
        <th>{{ animal.animal_type }}</th>
    </tr>
    <tr>
        <th>Имя животного</th>
        <th>{{ animal.animal_name }}</th>
    </tr>
    <tr>
        <th>Фото животного</th>
        <th><img src="{{ animal.animal_photo }}" alt="Фото животного не найдено"></th>
    </tr>
    </table>
    <br><hr><br>
    <a href="/master">Назад</a>

{% endblock %}

ЛР-4/LAB_4/templates/master/list.html
{% extends 'base.html' %}

{% block title %}ЛР №4{% endblock %}

{% block content %}

    <center><h1>Список животных</h1></center><hr><br>

    {% if a_list %}
        {% for a in a_list %}
            <a href="{% url 'master:detail' a.id %}">{{ a.animal_name }}</a><br>
        {% endfor %}
    {% else %}
        Список пуст
    {% endif %}

{% endblock %}